name: fraud Detection apiVersion

on: push

jobs:
  project-testing:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: setup Python
      uses: actions/setup-python@v6
      with:
        python-version:  3.13.2

    - name: Cache pip dependencies
      uses: actions/cache@v5
      with: 
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: run pipeline
      env:
        DAGSHUB_AUTH_TOKEN: ${{ secrets.DAGSHUB_AUTH_TOKEN }}
        MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }}
        
      run: |
        dvc repro

    - name: login to AWS ECR 
      if: success()
      run: |
         aws config set aws_access_key_id ${{secrets.AWS_ACCESS_KEY_ID}}  
         aws config set aws_secret_access_key ${{secrets.AWS_SECRET_ACCESS_KEY}}
         aws config set region ${{secrets.AWS_REGION}}\
         aws ecr get-login-password --region ${{secrets.AWS_REGION}} | docker login --username AWS --password-stdin ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.${{secrets.AWS_REGION}}.amazonaws.com

    - name: Build Docker image
      run: |
        docker build -t fraud-detection:latest .  

    - name: Tag Docker image
      run: |
        docker tag fraud-detection:latest \${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.${{secrets.AWS_REGION}}.amazonaws.com/fraud-detection:latest 

    - name: check docker authentication
      run: docker info

    - name: push docker image to ECR
      run:
        docker push ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.${{secrets.AWS_REGION}}.amazonaws.com/fraud-detection:latest
      